DotNetCoders/DotNetCoders/Models/SupplierView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DotNetCoders.Model.Model;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace DotNetCoders.Models
{
    public class SupplierView
    {
        public int Id { get; set; }
        [Display(Name = " Code ")]
        [Required(ErrorMessage = "Please enter code")]
        [MaxLength(4, ErrorMessage = "Code must be in 4 characters")]
        [MinLength(4, ErrorMessage = "Code must be in 4 characters")]
        public string Code { get; set; }
        [Display(Name = " Name ")]
        [Required(ErrorMessage = "Please enter name")]
        public string Name { get; set; }
        [Display(Name = " Address ")]
        public string Address { get; set; }
        [Display(Name = " Email ")]
        [Required(ErrorMessage = "Please enter email")]
        [EmailAddress]
        [RegularExpression("^[_A-Za-z'`+-.]+([_A-Za-z0-9'+-.]+)*@([A-Za-z0-9-])+(\\.[A-Za-z0-9]+)*(\\.([A-Za-z]*){3,})$", ErrorMessage = "Enter proper email")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Format not proper of email address")]
        public string Email { get; set; }
        [Display(Name = " Contact ")]
        [Required(ErrorMessage = "Please enter contact no")]
        [RegularExpression("([01][0-9]*)", ErrorMessage = "Point must be digits")]
        [MaxLength(11, ErrorMessage = "Contact number must be in 11 digits")]
        [MinLength(11, ErrorMessage = "Contact number must be in 11 digits")]
        public string Contact { get; set; }
        [Display(Name = " Contact Person")]
        public string ContactPerson { get; set; }
        public List<Supplier> Suppliers { get; set; }
    }
}

DotNetCoders/DotNetCoders/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using DotNetCoders.Manager.Manager;
using DotNetCoders.Model.Model;
using DotNetCoders.Models;

namespace DotNetCoders.Controllers
{
    public class SupplierController : Controller
    {
        SupplierManager _supplierManager = new SupplierManager();
        [HttpGet]
        public ActionResult Add(int id)
        {
            SupplierView supplierView = new SupplierView();
            ViewBag.ActionName = "Show Supplier";
            if (id != 0)
            {
                Supplier supplier = _supplierManager.GetById(id);
                supplierView = Mapper.Map<SupplierView>(supplier);
                ViewBag.Head = "Update";
                ViewBag.ButtonName = "Update";
                ViewBag.Message = null;
            }
            else
            {
                ViewBag.Message = null;
                ViewBag.Head = "Add";
                ViewBag.ButtonName = "Save";
            }
            return View(supplierView);
        }
        [HttpPost]
        public ActionResult Add(SupplierView supplierView)
        {
            string message = null;
            ViewBag.ActionName = "Add";
            ViewBag.ButtonName = "Save";
            ViewBag.Head = "Add";
            Supplier supplier = Mapper.Map<Supplier>(supplierView);

            if (supplierView.Id != 0)
            {
                ViewBag.ActionName = "Show";
                if (_supplierManager.Update(supplier))
                {
                    message = "Supplier is updated successfully";
                }
            }
            else
            {

                message = _supplierManager.Add(supplier) ? "Supplier is saved successfully" : "Supplier is not saved";
            }

            ViewBag.Message = message;
            ViewBag.Save = "save";
            ModelState.Clear();
            return View(new SupplierView());

        }
        [HttpGet]
        public ActionResult Show()
        {
            SupplierView supplierView = new SupplierView { Suppliers = _supplierManager.GetAll() };
            ViewBag.Show = "Show";
            ViewBag.ActionName = "Add";
            return View(supplierView);
        }
        public ActionResult Show(int id, string search)
        {
            SupplierView supplierView;
            ViewBag.Show = "Show";
            ViewBag.ActionName = "Add";
            if (search == null)
            {
                ViewBag.Message = _supplierManager.Delete(id) ? "Deleted" : "Not deleted";
                supplierView = new SupplierView { Suppliers = _supplierManager.GetAll() };
            }
            else
            {
                supplierView = new SupplierView { Suppliers = _supplierManager.SearchSuppliers(search) };
            }
            return View(supplierView);
        }
        public JsonResult GetSupplierCode(SupplierView supplier)
        {
            return Json(!_supplierManager.GetAll().Any(x => x.Code == supplier.Code && x.Id != supplier.Id), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetSupplierContact(SupplierView supplier)
        {
            return Json(!_supplierManager.GetAll().Any(x => x.Contact == supplier.Contact && x.Id != supplier.Id), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetSupplierEmail(SupplierView supplier)
        {
            return Json(!_supplierManager.GetAll().Any(x => x.Email == supplier.Email && x.Id != supplier.Id), JsonRequestBehavior.AllowGet);
        }
    }
}

DotNetCoders/DotNetCoders/Views/Supplier/Add.cshtml
@model DotNetCoders.Models.SupplierView
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Add";
}
@section MyStyles
{
    <style>
        input[type=number]::-webkit-inner-spin-button,
        input[type=number]::-webkit-outer-spin-button {
            -webkit-appearance: none;
        }

        input[type=number] {
            -moz-appearance: textfield;
        }
    </style>
}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="form-inline">
            <div class="form-group">
                @using (Html.BeginForm("Show", "Supplier", null, FormMethod.Get, new { @style = "max-width: 700px; margin: 0 180px 0 0" }))
                {
                    <button pull-left type="submit" class="btn btn-info" style="background: #254558"> Show Supplier </button>
                }
            </div>&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="form-group">
                @using (Html.BeginForm("Show", "Supplier", FormMethod.Post, new { @style = "max-width: 700px; margin: auto" }))
                {
                    <input type="hidden" name="id" value=0 />
                    @Html.TextBox("search", null, htmlAttributes: new { @class = "form-control", @style = "width: 200px", @type = "text", placeholder = "Search by Name, Contact, Email" })
                    <button type="submit" class="btn btn-info fa fa-search icon" style="background: #254558" pull-right> search</button>
                }
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-header card-header-primary" style="background: #447fa2">
                <h4 class="card-title"> @ViewBag.Head Category</h4>
            </div>
            <div class="card-body">
                @using (Html.BeginForm((string)ViewBag.Submit, "Supplier", FormMethod.Post, htmlAttributes: new { @style = "max-width: 700px; margin: auto" }))
                {
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-5">
                            <div class="form-group">
                                @Html.TextBoxFor(c => c.Id, htmlAttributes: new { @type = "hidden" })
                                @Html.LabelFor(c => c.Code, htmlAttributes: new { @class = "bmd-label-floating" })

                                @Html.TextBoxFor(c => c.Code, htmlAttributes: new
                                {
                                    @class = "form-control",
                                    @type = "text",
                                    @placeholder = "Code",
                                })
                                @Html.ValidationMessageFor(c => c.Code, null, htmlAttributes: new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                @Html.LabelFor(c => c.Name, htmlAttributes: new { @class = "bmd-label-floating" })

                                @Html.TextBoxFor(c => c.Name, htmlAttributes: new
                                {
                                    @class = "form-control",
                                    @type = "text",
                                    @placeholder = "Name",
                                })
                                @Html.ValidationMessageFor(c => c.Name, null, htmlAttributes: new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-5">
                            <div class="form-group">
                                @Html.LabelFor(c => c.Address, htmlAttributes: new { @class = "bmd-label-floating" })

                                @Html.TextBoxFor(c => c.Address, htmlAttributes: new
                                {
                                    @class = "form-control",
                                    @type = "text",
                                    @placeholder = "Address",
                                })
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                @Html.LabelFor(c => c.Email, htmlAttributes: new { @class = "bmd-label-floating" })

                                @Html.TextBoxFor(c => c.Email, htmlAttributes: new
                                {
                                    @class = "form-control",
                                    @type = "email",
                                    @placeholder = "Email",
                                })
                                @Html.ValidationMessageFor(c => c.Email, null, htmlAttributes: new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-5">
                            <div class="form-group">
                                @Html.LabelFor(c => c.Contact, htmlAttributes: new { @class = "bmd-label-floating" })

                                @Html.TextBoxFor(c => c.Contact, htmlAttributes: new
                                {
                                    @class = "form-control",
                                    @type = "number",
                                    @placeholder = "Contact",
                                })
                                @Html.ValidationMessageFor(c => c.Contact, null, htmlAttributes: new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                @Html.LabelFor(c => c.ContactPerson, htmlAttributes: new { @class = "bmd-label-floating" })

                                @Html.TextBoxFor(c => c.ContactPerson, htmlAttributes: new
                                {
                                    @class = "form-control",
                                    @type = "text",
                                    @placeholder = "Contact Person",
                                })
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-info pull-right" style="background: #254558">@ViewBag.ButtonName</button>
                    <div class="clearfix"></div>
                }
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>


<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        @if (ViewBag.Message != null)
        {
            <div class="alert alert-success" style="margin: auto">@ViewBag.Message</div>
        }
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row">
    <div class="col-md-1"></div>

</div>
<div class="row">
    <div class="col-md-1"></div>

</div>
<div class="row">
    <div class="col-md-1"></div>

</div>


@section MyScripts
{
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

DotNetCoders/DotNetCoders/Views/Supplier/Show.cshtml
@model DotNetCoders.Models.SupplierView
@{
    ViewBag.Title = "Show";
	 Layout = "~/Views/Shared/_Layout.cshtml";
}

@section MyStyles
{
    <style>

        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        th {
            background: darkslateblue;
            text-align: center;
            padding: 10px;
            color: azure;
        }

        td {
            border: 1px solid #dddddd;
            text-align: center;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
}

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="form-inline">
            <div class="form-group">
                @using (Html.BeginForm("Add", "Supplier", new { id = 0 }, FormMethod.Get, new { @style = "max-width: 700px; margin: 0 180px 0 0" }))
                {
                    <button pull-left type="submit" class="btn btn-info" style="background: #254558"> @ViewBag.ActionName Supplier</button>
                }
            </div>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="form-group">
                @using (Html.BeginForm("Show", "Supplier", FormMethod.Post, new { @style = "max-width: 700px; margin: auto" }))
                {
                    <input type="hidden" name="id" value=0 />
                    @Html.TextBox("search", null, htmlAttributes: new { @class = "form-control", @style = "width: 200px", @type = "text", placeholder = "Search by Name, Contact, Email" })
                    <button type="submit" class="btn btn-info fa fa-search icon" style="background: #254558" pull-right> search</button>
                }
            </div>
        </div>
    </div>
</div>

<div>
    @{
        Html.RenderPartial("Supplier/_SupplierShow", Model);
    }
</div>