DotNetCoders/DotNetCoders/Models/PurchaseView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using DotNetCoders.Model.Model;

namespace DotNetCoders.Models
{
    public class PurchaseView
    {
        public PurchaseView()
        {
            PurchaseProductInfo = new PurchaseProductInfo();
            PurchaseInfos = new List<PurchaseInfo>();
            PurchaseProductInfos = new List<PurchaseProductInfo>();
            Supplier = new Supplier();
            Product = new Product();
            Category = new Category();
            ProductSelectListItems = new List<SelectListItem>();
            ProductName = new List<string>();
            ProductCode = new List<string>();
            TotalPrices = new List<string>(); 
        }
        //selfproperty
        public Supplier Supplier { get; set; }
        public List<SelectListItem> SupplierSelectListItems { get; set; }
        public Category Category { get; set; }
        public List<SelectListItem> CategorySelectListItems { get; set; }
        public Product Product { get; set; }
        public List<SelectListItem> ProductSelectListItems { get; set; }
        public int AvailableQuantity { get; set; }
        public double PreviousUnitPrice { get; set; }
        public double PreviousMRP { get; set; }
        public double TotalPrice { get; set; }
        public List<string> ProductName { get; set; }
        public List<string> ProductCode { get; set; }
        public List<string> TotalPrices { get; set; }

        //purchase property
        [Required]
        public PurchaseInfo PurchaseInfo { get; set; }


        //purchaseproduct property

        public List<PurchaseInfo> PurchaseInfos { get; set; }
        public List<PurchaseProductInfo> PurchaseProductInfos { get; set; }
        [Required]
        public PurchaseProductInfo PurchaseProductInfo { get; set; }

    }
}

DotNetCoders/DotNetCoders/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using DotNetCoders.Manager.Manager;
using DotNetCoders.Model.Model;
using DotNetCoders.Models;

namespace DotNetCoders.Controllers
{
    public class CustomerController : Controller
    {
        CustomerManager _customerManager = new CustomerManager();
        // GET: Customer
        
        [HttpGet]
        public ActionResult Add(int id)
        {
            CustomerView customerView = new CustomerView();
            ViewBag.ActionName = "Show Customer";
            if (id != 0)
            {
                Customer customer = _customerManager.GetById(id);
                customerView = Mapper.Map<CustomerView>(customer);
                ViewBag.Head = "Update";
                ViewBag.ButtonName = "Update";
                ViewBag.Message = null;
            }
            else
            {
                ViewBag.Message = null;
                ViewBag.Head = "Add";
                ViewBag.ButtonName = "Save";
            }
            return View(customerView);
        }
        [HttpPost]
        public ActionResult Add(CustomerView customerView)
        {
            string message = null;
            ViewBag.ActionName = "Add";
            ViewBag.ButtonName = "Save";
            ViewBag.Head = "Add";
            Customer customer = Mapper.Map<Customer>(customerView);

            if (customerView.Id != 0)
            {
                ViewBag.ActionName = "Show";
                if (_customerManager.Update(customer))
                {
					message = "Customer is updated successfully";
                }
            }
            else
            {

                message = _customerManager.Add(customer) ? "Customer is saved successfully" : "Customer is not saved";
            }

            ViewBag.Message = message;
            ViewBag.Save = "save";
            ModelState.Clear();
            return View(new CustomerView());
           
        }
        [HttpGet]
        public ActionResult Show()
        {
            CustomerView customerView = new CustomerView {Customers = _customerManager.GetAll()};
             ViewBag.Show = "Show";
            ViewBag.ActionName = "Add";			
			return View(customerView);			
        }
        public ActionResult Show(int id, string search)
        {
            CustomerView customerView;
            ViewBag.Show = "Show";
            ViewBag.ActionName = "Add";
            if (search == null)
            {
                ViewBag.Message = _customerManager.Delete(id) ? "Deleted" : "Not deleted";
                customerView = new CustomerView { Customers = _customerManager.GetAll() };
            }
            else
            {
                customerView = new CustomerView { Customers = _customerManager.SearchCustomers(search) };
            }
            return View(customerView);
        }
        public JsonResult GetCustomerCode(CustomerView customer)
        {
            return Json(!_customerManager.GetAll().Any(x => x.Code == customer.Code && x.Id != customer.Id), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCustomerContact(CustomerView customer)
        {
            return Json(!_customerManager.GetAll().Any(x => x.Contact == customer.Contact && x.Id != customer.Id), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCustomerEmail(CustomerView customer)
        {
            return Json(!_customerManager.GetAll().Any(x => x.Email == customer.Email && x.Id != customer.Id), JsonRequestBehavior.AllowGet);
        }
    }
}

DotNetCoders/DotNetCoders/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using DotNetCoders.Manager.Manager;
using DotNetCoders.Model.Model;
using DotNetCoders.Models;

namespace DotNetCoders.Controllers
{
    public class PurchaseController : Controller
    {
        PurchaseManager _PurchaseManager = new PurchaseManager();
        SupplierManager _supplierManager = new SupplierManager();
        CategoryManager _categoryManager = new CategoryManager();
        ProductManager _productManager = new ProductManager();
        // GET: Purchase
        private PurchaseView aPurchaseView = new PurchaseView();
        [HttpGet]
        public ActionResult Add()
        {
            PurchaseInitialize();
            ViewBag.Message = null;
            return View(aPurchaseView);
        }

        private void PurchaseInitialize()
        {
            aPurchaseView.PurchaseInfo = new PurchaseInfo {Date = DateTime.Today};
            aPurchaseView.CategorySelectListItems = _categoryManager
                .GetAll()
                .Select(c => new SelectListItem() {Value = c.Id.ToString(), Text = c.Name}
                ).ToList();

            aPurchaseView.SupplierSelectListItems = _supplierManager
                .GetAll()
                .Select(s => new SelectListItem() {Value = s.Id.ToString(), Text = s.Name}
                ).ToList();
        }

        [HttpPost]
        public ActionResult Add(PurchaseView purchaseView)
        {
            
                PurchaseInfo aPurchaseInfo = purchaseView.PurchaseInfo;
                ViewBag.Message = _PurchaseManager.Insert(aPurchaseInfo) ? "Purchase is saved" : "Purchase is not Saved";
            aPurchaseView = new PurchaseView();
            PurchaseInitialize();

            return View(aPurchaseView);
        }

        [HttpGet]
        public ActionResult Show()
        {
            PurchaseView purchaseView = new PurchaseView {PurchaseInfos = _PurchaseManager.Show()};
            ViewBag.product = null;
            return View(purchaseView);
        }
        [HttpPost]
        public ActionResult Show(string search)
        {
            PurchaseView purchaseView = new PurchaseView {PurchaseInfos = _PurchaseManager.Search(search)};
            ViewBag.product = null;
            return View(purchaseView);
        }
        public JsonResult Details(int id)
        {
            aPurchaseView.PurchaseProductInfos = _PurchaseManager.Details(id);
            //PurchaseView aPurchaseView = new PurchaseView();
            //aPurchaseView.PurchaseInfos = _PurchaseManager.Show();
            //List<PurchaseProductInfo> query = new List<PurchaseProductInfo>();
            //query = 
            foreach (var product in aPurchaseView.PurchaseProductInfos)
            {
                var name = _productManager.GetById(product.ProductId);
                aPurchaseView.ProductName.Add(name.Name);
                aPurchaseView.ProductCode.Add(name.Code);
                var totalPrice = product.Quantity * product.UnitPrice;
                aPurchaseView.TotalPrices.Add(totalPrice.ToString());
            }
            var x = aPurchaseView;
            return Json(x, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBillNo(PurchaseInfo purchaseInfo)
        {
            return Json(!_PurchaseManager.Show().Any(x => x.InvoiceNo == purchaseInfo.InvoiceNo && x.Id != purchaseInfo.Id), JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult AjaxMethod(string type, int value)
        {
            switch (type)
            {
                case "Category_Id":
                    aPurchaseView.ProductSelectListItems = _productManager
                        .GetAllByCategory(value)
                        .Select(p => new SelectListItem() { Value = p.Id.ToString(), Text = p.Name }
                        ).ToList();
                    break;
                case "Product_Id":
                    List<string> productPurchaseInfo = _PurchaseManager.PurchaseView(value);
                    aPurchaseView.Product.Code = productPurchaseInfo[0];
                    aPurchaseView.AvailableQuantity = Convert.ToInt32(productPurchaseInfo[1]);
                    aPurchaseView.PreviousUnitPrice = Convert.ToDouble(productPurchaseInfo[2]);
                    aPurchaseView.PreviousMRP = Convert.ToDouble(productPurchaseInfo[3]);
                    break;
            }
            return Json(aPurchaseView);
        }
    }
}

DotNetCoders/DotNetCoders/Views/Purchase/Show.cshtml
@model DotNetCoders.Models.PurchaseView
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Show";
}

@section MyStyles
{
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        th {
            background: darkslateblue;
            text-align: center;
            padding: 10px;
            color: azure;
        }

        td {
            border: 1px solid #dddddd;
            text-align: center;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
}

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="form-inline">
            <div class="form-group">
                @using (Html.BeginForm("Add", "Purchase", new { page = ViewBag.ActionName }, FormMethod.Get, new { @style = "max-width: 700px; margin: 0 180px 0 0" }))
                {
                    <button type="submit" class="btn btn-info" style="background: #254558"> New Purchase </button>
                }
            </div>
            <div class="form-group">
                @using (Html.BeginForm("Show", "Purchase", FormMethod.Post, new { @style = "max-width: 700px; margin: auto" }))
                {
                    @Html.TextBox("search", null, htmlAttributes: new { @class = "form-control", @style = "width: 200px", @type = "text", placeholder = "Search by Name, Email, Contact" })
                    <button type="submit" class="btn btn-info fa fa-search icon" style="background: #254558"> search</button>
                }
            </div>
        </div>


    </div>
    @*@Html.ActionLink(, "Add", "Customer", htmlAttributes:new { @class = "form-group btn btn-default fa fa-plus-circle icon", @style = "margin: 0 40% 0 0"  })*@
</div>


<table>
    <tr>
        <th>Sl</th>
        <th>Date</th>
        <th>Purchase Code</th>
        <th>Supplier</th>
        <th>Invoice No</th>
        <th>Action</th>
    </tr>
    @{ int sl = 0;}
    @foreach (var purchase in Model.PurchaseInfos)
    {
        <tr>
            <td>@(++sl)</td>
            <td>@purchase.Date</td>
            <td>@purchase.Code</td>
            <td>@purchase.Supplier.Name</td>
            <td>@purchase.InvoiceNo</td>
            <td>

                @Html.ActionLink("Details", null, null, new { @class = "btn-info", @style = "padding: 8px; border-radius: 8px", @id = purchase.Id })
                @*@Html.ActionLink("Delete", "Delete", "Customer", new { id = std.Id }, null)*@
            </td>
        </tr>
    }
</table>

<br /><br /><br />

<table>
    <thead>
        <tr>
            <th>Sl</th>
            <th>Code</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>UnitPrice</th>
            <th>MRP</th>
            <th>TotalPrice</th>
        </tr>
    </thead>
    <tbody id="productAll"></tbody>


</table>


@section MyScripts
{
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript">
        $(document).on('click', 'a.btn-info', function () { // <-- changes
            var id = $(this).attr("id");
                var jsonData = { id: id };
                $.ajax({
                    type: "POST",
                    url: "/Purchase/Details",
                    data: jsonData,
                    //contentType: "application/json; charset=utf-8",
                    //dataType: "json",
                    success: function (response) {
                        $("#productAll").empty();
                        var j = 0;
                        $.each(response.PurchaseProductInfos,
                            function (i, item) {
                                //var totalPrice = parseFloat(item.Quantity) * parseFloat(item.UnitPrice);
                                $("#productAll").append(
                                    $('<tr>'),
                                    $('<td>').text(++i), $('</td>'),
                                    $('<td>').text(response.ProductCode[j]), $('</td>'),
                                    $('<td>').text(response.ProductName[j]), $('</td>'),
                                    $('<td>').text(item.Quantity), $('</td>'),
                                    $('<td>').text(item.UnitPrice), $('</td>'),
                                    $('<td>').text(item.MRP), $('</td>'),
                                    $('<td>').text(response.TotalPrices[j]), $('</td>'), $('</tr>')
                                );
                                j++;
                            });
                        
                    },
                    failure: function (response) {
                        alert('no'); //response.responseText
                    },
                    error: function (response) {
                        alert('error');
                    }
                });

                return false;
        });

    </script>
}