DotNetCoders/DotNetCoders/Models/SalesReportView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DotNetCoders.Models
{
    public class SalesReportView
    {
        public string Code { get; set; }
        public string Product { get; set; }
        public string Category { get; set; }
        public int SoldQuantity { get; set; }
        public double CostPrice { get; set; }
        public double SalesPrice { get; set; }
        public double Profit { get; set; }
        public DateTime startDate { get; set; }
        public DateTime endDate { get; set; }
    }
}

DotNetCoders/DotNetCoders/Controllers/SalesReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotNetCoders.Manager.Manager;
using DotNetCoders.Models;
using Rotativa;
namespace DotNetCoders.Controllers
{
    public class SalesReportController : Controller
    {
        // GET: SalesReport
        SalesManager _salesManager = new SalesManager();
        [HttpGet]
        public ActionResult Index()
        {
            SalesReportView aSalesReportView = new SalesReportView();
            aSalesReportView.startDate = DateTime.MinValue;
            aSalesReportView.endDate = DateTime.MaxValue;
            var salesReportViews = _salesManager.SalesReportViews(DateTime.MinValue, DateTime.MaxValue);
            ViewBag.Message = null;
            ViewBag.Report = salesReportViews;
            return View(aSalesReportView);
        }
        [HttpPost]
        public ActionResult Index(DateTime startDate, DateTime endDate)
        {
            var salesReportViews = _salesManager.SalesReportViews(startDate, endDate);
            if (salesReportViews.Count < 1)
            {
                ViewBag.Message = "No Data Found";
            }

            ViewBag.Report = salesReportViews;
            return View();
        }
        [HttpGet]
        public ActionResult GetSalesReport(DateTime startDate, DateTime endDate)
        {

            var report = new ActionAsPdf("SalesReportPdf", new{ startDate , endDate }) { FileName = "SalesReportPdf.pdf" };
            return report;
        }

        public ActionResult SalesReportPdf(DateTime startDate, DateTime endDate)
        {

            var salesReportViews = _salesManager.SalesReportViews(startDate,endDate);
            ViewBag.Report = salesReportViews;
            return View();
        }
    }
}

DotNetCoders/DotNetCoders/Views/SalesReport/Index.cshtml
@model DotNetCoders.Models.SalesReportView
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section MyStyles
{
    <style>
        h2 {
            color: white;
            text-align: center;
            margin-bottom: 2%;
            margin-top: 1%;
            text-transform: uppercase;
            font-weight: bold;
            letter-spacing: 1px;
            text-decoration-color: turquoise;
            background: rgb(107, 194, 130);
        }

        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        th {
            background: darkslateblue;
            text-align: center;
            padding: 10px;
            color: azure;
        }

        td {
            border: 1px solid #dddddd;
            text-align: center;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
}
<h2>Sales &nbsp;&nbsp; Report</h2>
@{ DateTime sDate = DateTime.Today; DateTime eDate = DateTime.Today;}

@using (Html.BeginForm("Index", "SalesReport", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-3">
            @Html.TextBox("startDate", (sDate), "{0:yyyy-MM-dd}", htmlAttributes: new
            {
                @class = "form-control",
                @type = "date",
                @id = "startDate"
            })
        </div>
        <div class="col-md-3">
            @Html.TextBox("endDate", (eDate), "{0:yyyy-MM-dd}", htmlAttributes: new
            {
                @class = "form-control",
                @type = "date",
                @id = "endDate"
            })
        </div>
        
        <div class="col-md-3">
            <input type="submit" value="submit" class="btn btn-info pull-left" style="background: #254558" />
        </div>
    </div>
}
<input type="hidden" id="hideStart" />
<input type="hidden" id="hideEnd" />
<div class="row">
    <table>
        <tr>
            <th>Sl</th>
            <th>Code</th>
            <th>Name</th>
            <th>Category</th>
            <th>Sold Quantity</th>
            <th>Cost Price (TK) </th>
            <th>Sales Price (Tk)</th>
            <th>Profit (Tk)</th>

        </tr>
        @{ int sl = 0;}
        @foreach (var sales in ViewBag.Report)
        {
            <tr>
                <td>@(++sl)</td>
                <td>@sales.Code</td>
                <td>@sales.Product</td>
                <td>@sales.Category</td>
                <td>@sales.SoldQuantity</td>
                <td>@sales.CostPrice</td>
                <td>@sales.SalesPrice</td>
                <td>@sales.Profit</td>

            </tr>
        }
        <tr>
            @if (ViewBag.Message != null)
            {
                <td colspan="8" class="alert alert-warning" role="alert" style="width: 100%">


                    @ViewBag.Message


                </td>
            }
        </tr>
    </table>
    @using (Html.BeginForm("GetSalesReport", "SalesReport", FormMethod.Get))
    {
        @Html.TextBoxFor(c => c.startDate, htmlAttributes: new
        {
            @id = "reportStart", @type= "hidden"

        })
        @Html.TextBoxFor(c => c.endDate, htmlAttributes: new
   {
       @id = "reportEnd",
       @type = "hidden"

   })
        <input type="submit" value="Download Sales Report as PDF" class = "btn btn-primary pull-right" style="background: #254558" target = "_blank"/>
    }    
    @*@Html.ActionLink("Download Sales Report as PDF", "GetSalesReport", "SalesReport", new { startDate = Model.startDate, endDate = Model.endDate }, new { @class = "btn btn-primary", @target = "_blank" })*@

</div>

@section MyScripts
{
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#startDate").change(function() {
                //alert($("#startDate").val());
                var start = $("#startDate").val();
                $("#reportStart").val(start);
                //alert($("#reportStart").val());
            });
            $("#endDate").change(function () {
                //alert($("#startDate").val());
                var start = $("#endDate").val();
                $("#reportEnd").val(start);
                //alert($("#reportEnd").val());
            });
        });
    </script>

}